### PR TITLE
Implemented the showing of a Diff for differing strings, like Rspec does.

### PR DESCRIPTION
**Pull request by CharString**
https://github.com/garybernhardt/expecter/issues/3

Works for strings and unicode.

Points of attention:
- Might break in Python 3 I have only tested it in 2.7
- Now that I read the issue again, perhaps I should test for newlines, right now a diff is shown for all failing str's and unicode's, not just long ones.

Let me know what you think.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Just some notes:
1. If you want to ensure python 2 is using unicode, put `from __future__ import unicode_literals` at the top. This will ensure forward compatibility with python 3 without needing to use the `u''` syntax which breaks in python 3.2 but now works in python 3.3
2. In the `.travis.yml` file, remove testing for 3.1 -- Travis no longer supports it -- and add 3.3 for laughs.
3. One last thing is that `basestring` doesn't exist in python3. You could steal a compatibility hack from [requests](https://github.com/kennethreitz/requests/blob/master/requests/compat.py#L85) which works very well to be safe.

Otherwise, this looks awesome! :+1:

**Comment by garybernhardt** [comment]
Seems good, but this does fail on Python 3, as predicted. If you run tox, it'll test against Python 2.6, 2.7, 3.1, and 3.2. Can you look at that?

**Comment by CharString** [comment]
Thanks for the feedback guys. I'll setup a machine with all the pythons and get this to an acceptable state.

**Comment by garybernhardt** [comment]
I just installed the binary distributions from the Python site and it all worked (on a Mac). Hopefully it goes esaily for you, too.

**Comment by CharString** [comment]
I have binaries installed for 2.7 and 3.2. Had to turn the symlink of README.txt into a hardlink, else REAMDE.txt would end up missing from the expecter.zip that tox creates. But I have failing tests for 3.2, now. Which is great. Hope to hack fixing those today.

**Comment by CharString** [comment]
Tested in 2.7 and 3.2.

**Comment by CharString** [comment]
And travis says 2.6 and 3.3 are green too.
https://www.travis-ci.org/garybernhardt/expecter/builds/4639481

**Comment by sigmavirus24** [comment]
@CharString, Travis is showing an error with building the docs. I doubt it is your fault because you didn't modify them, but did you see that on your local tests?

**Comment by garybernhardt** [comment]
I like the part where the tests fail but apparently return with status 0. :/ Looking at it now.

**Comment by garybernhardt** [comment]
Looks like everything works now. Thanks!

**Pull request merged**
