### PR TITLE
Allow isinstance to take multiple classes.

### PR DESCRIPTION
**Pull request by sigmavirus24**
e.g.

``` python
expect('str').isinstance((str, bytes))
```

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I guess I should better explain this. You can do the following without a problem:

``` python
assert isinstance(spam, (str, bytes)), ('Expected an instance of str or bytes but got instance of %s' % spam.__class__.__name__)
```

But as expecter was written, one could not pass a tuple like that since expecter was relying on the fact that someone would only pass one class. You could write this in fewer lines, but I suspect using a conditional saves time. The simplification would be:

``` python
def isinstance(self, expected_cls):
    expected_cls = tuple(expected_cls)
    cls_name = ' or '.join([e.__name__ for e in expected_cls])
    assert isinstance(self._actual, expected_cls), (
        'Expected an instance of %s but got an instance of %s' % (cls_name, self._actual.__class__.__name__))
```

**Comment by garybernhardt** [comment]
Can you add a test? (And, if you're feeling compassionate toward Emacs users, re-add those trailing new lines? I don't use Emacs, but they're in enough pain as it is. ;)

**Comment by sigmavirus24** [comment]
Those new lines are offensive to flake8 (a linter/PEP 8 checker) which is the only reason I removed them. I'll put them back though and add a test in a second.

**Comment by sigmavirus24** [comment]
I rebased as well so the merge should go cleanly.

**Comment by garybernhardt** [comment]
Thanks!

**Pull request merged**
